### ISSUE TITLE
Add ability to generate config

### ISSUE THREAD

**Issue by achiurizo** [subspace/pulsar#1]
:clipboard: [CLI Spec](https://www.notion.so/subspacelabs/CLI-Wrapper-DRAFT-4612350a0d834a40834e43ff33572642)

- [x] Follows the [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) spec
- [x] Generates a Default TOML config (exact fields TBD)

The CLI should allow the ability to generate a default config, like so:

```toml
# $HOME/.config/subspace/settings
[farmer]
address = "WALLET_ADDRESS"
plot_directory = ""
plot_size = "100GB"
opencl = false

[node]
chain = "gemini-2a"
execution = "wasm"
blocks-pruning = 1024
state-pruning = 1024
validator = true
name = "hostname"
port = 30333
unsafe-ws-external = true # not sure we need this
```

---

```gherkin
Given I do not have a config
When I run `subspace init`
Then I should be prompted to generate a config
```
